Eeg preprocessing
smathot/eeg_eyetracking_parser pull request #1
Opened 2022-06-27 14:32 UTC by HermineBerberyan

2022-06-28 08:51 UTC, smathot requested changes
Thank you. A few requests for changes and then I will merge it. It seems to work, but because of the downsample-events issue, I haven't been able to properly test it, so I'll try this again after these changes.

2022-06-28 08:51 UTC, smathot commented on eeg_eyetracking_parser/_eeg_preprocessing.py
> +    raw_unfiltered = raw.copy()
Only create unfiltered copy if it is actually used.

2022-06-28 08:51 UTC, smathot commented on eeg_eyetracking_parser/_eeg_preprocessing.py
> +    empty_chan_names = [chan_name for chan_name in raw.info['ch_names'] if chan_name.startswith(chan_name_pattern)]
Avoid lines > 79 characters (here and elsewhere)

2022-06-28 08:51 UTC, smathot commented on eeg_eyetracking_parser/_eeg_preprocessing.py
> +    return raw
Functions that modify the `raw` in place shouldn't return the `raw`. This behavior should be clearly described in the docstring.

2022-06-28 08:51 UTC, smathot commented on eeg_eyetracking_parser/_eeg_preprocessing.py
> +    """
Describe arguments in docstrings using numpydoc format (here and elsewhere). Also describe the behavior of the function, for example how it changes the `raw` object by modifying the signal or the `info` property.

2022-06-28 08:51 UTC, smathot commented on eeg_eyetracking_parser/_eeg_preprocessing.py
> +def downsample_data(raw, srate=256):
Event timestamps should also be adjusted. (Due to the way that the EEG and eye-tracking data are merged, we cannot first downsample and then extract the events from the annotations, or at least not easily.)

2022-06-29 09:13 UTC, HermineBerberyan commented on eeg_eyetracking_parser/_eeg_preprocessing.py
> +    raw_unfiltered = raw.copy()
It is used in plotting

2022-06-29 14:31 UTC, merged